export interface OcrLanguage {
  code: string;
  label: string;
}

/**
 * Every language with a tesseract traineddata model published in the
 * `@tesseract.js-data` scope on npm (verified against the CDN). Downloads use
 * the higher-quality `4.0.0_best_int` models; the few languages that only ship
 * `4.0.0` fall back automatically in the main process.
 */
export const OCR_LANGUAGES: OcrLanguage[] = [
  { code: "afr", label: "Afrikaans" },
  { code: "amh", label: "Amharic" },
  { code: "ara", label: "Arabic" },
  { code: "asm", label: "Assamese" },
  { code: "aze", label: "Azerbaijani" },
  { code: "aze_cyrl", label: "Azerbaijani (Cyrillic)" },
  { code: "bel", label: "Belarusian" },
  { code: "ben", label: "Bengali" },
  { code: "bod", label: "Tibetan" },
  { code: "bos", label: "Bosnian" },
  { code: "bre", label: "Breton" },
  { code: "bul", label: "Bulgarian" },
  { code: "cat", label: "Catalan" },
  { code: "ceb", label: "Cebuano" },
  { code: "ces", label: "Czech" },
  { code: "chi_sim", label: "Chinese (Simplified)" },
  { code: "chi_sim_vert", label: "Chinese (Simplified, vertical)" },
  { code: "chi_tra", label: "Chinese (Traditional)" },
  { code: "chi_tra_vert", label: "Chinese (Traditional, vertical)" },
  { code: "chr", label: "Cherokee" },
  { code: "cos", label: "Corsican" },
  { code: "cym", label: "Welsh" },
  { code: "dan", label: "Danish" },
  { code: "dan_frak", label: "Danish (Fraktur)" },
  { code: "deu", label: "German" },
  { code: "deu_frak", label: "German (Fraktur)" },
  { code: "div", label: "Dhivehi" },
  { code: "dzo", label: "Dzongkha" },
  { code: "ell", label: "Greek" },
  { code: "eng", label: "English" },
  { code: "enm", label: "English (Middle)" },
  { code: "epo", label: "Esperanto" },
  { code: "equ", label: "Equations" },
  { code: "est", label: "Estonian" },
  { code: "eus", label: "Basque" },
  { code: "fao", label: "Faroese" },
  { code: "fas", label: "Persian" },
  { code: "fil", label: "Filipino" },
  { code: "fin", label: "Finnish" },
  { code: "fra", label: "French" },
  { code: "frk", label: "German (Fraktur, old)" },
  { code: "frm", label: "French (Middle)" },
  { code: "fry", label: "Western Frisian" },
  { code: "gla", label: "Scottish Gaelic" },
  { code: "gle", label: "Irish" },
  { code: "glg", label: "Galician" },
  { code: "grc", label: "Greek (Ancient)" },
  { code: "guj", label: "Gujarati" },
  { code: "hat", label: "Haitian Creole" },
  { code: "heb", label: "Hebrew" },
  { code: "hin", label: "Hindi" },
  { code: "hrv", label: "Croatian" },
  { code: "hun", label: "Hungarian" },
  { code: "hye", label: "Armenian" },
  { code: "iku", label: "Inuktitut" },
  { code: "ind", label: "Indonesian" },
  { code: "isl", label: "Icelandic" },
  { code: "ita", label: "Italian" },
  { code: "ita_old", label: "Italian (Old)" },
  { code: "jav", label: "Javanese" },
  { code: "jpn", label: "Japanese" },
  { code: "jpn_vert", label: "Japanese (vertical)" },
  { code: "kan", label: "Kannada" },
  { code: "kat", label: "Georgian" },
  { code: "kat_old", label: "Georgian (Old)" },
  { code: "kaz", label: "Kazakh" },
  { code: "khm", label: "Khmer" },
  { code: "kir", label: "Kyrgyz" },
  { code: "kmr", label: "Kurdish (Kurmanji)" },
  { code: "kor", label: "Korean" },
  { code: "kor_vert", label: "Korean (vertical)" },
  { code: "kur", label: "Kurdish" },
  { code: "kur_ara", label: "Kurdish (Arabic)" },
  { code: "lao", label: "Lao" },
  { code: "lat", label: "Latin" },
  { code: "lav", label: "Latvian" },
  { code: "lit", label: "Lithuanian" },
  { code: "ltz", label: "Luxembourgish" },
  { code: "mal", label: "Malayalam" },
  { code: "mar", label: "Marathi" },
  { code: "mkd", label: "Macedonian" },
  { code: "mlt", label: "Maltese" },
  { code: "mon", label: "Mongolian" },
  { code: "mri", label: "Maori" },
  { code: "msa", label: "Malay" },
  { code: "mya", label: "Burmese" },
  { code: "nep", label: "Nepali" },
  { code: "nld", label: "Dutch" },
  { code: "nor", label: "Norwegian" },
  { code: "occ", label: "Occitan" },
  { code: "oci", label: "Occitan (post-1500)" },
  { code: "ori", label: "Odia (Oriya)" },
  { code: "osd", label: "Orientation & script detection" },
  { code: "pan", label: "Punjabi" },
  { code: "pol", label: "Polish" },
  { code: "por", label: "Portuguese" },
  { code: "pus", label: "Pashto" },
  { code: "que", label: "Quechua" },
  { code: "ron", label: "Romanian" },
  { code: "rus", label: "Russian" },
  { code: "san", label: "Sanskrit" },
  { code: "sin", label: "Sinhala" },
  { code: "slk", label: "Slovak" },
  { code: "slk_frak", label: "Slovak (Fraktur)" },
  { code: "slv", label: "Slovenian" },
  { code: "snd", label: "Sindhi" },
  { code: "spa", label: "Spanish" },
  { code: "spa_old", label: "Spanish (Old)" },
  { code: "sqi", label: "Albanian" },
  { code: "srp", label: "Serbian" },
  { code: "srp_latn", label: "Serbian (Latin)" },
  { code: "sun", label: "Sundanese" },
  { code: "swa", label: "Swahili" },
  { code: "swe", label: "Swedish" },
  { code: "syr", label: "Syriac" },
  { code: "tam", label: "Tamil" },
  { code: "tat", label: "Tatar" },
  { code: "tel", label: "Telugu" },
  { code: "tgk", label: "Tajik" },
  { code: "tgl", label: "Tagalog" },
  { code: "tha", label: "Thai" },
  { code: "tir", label: "Tigrinya" },
  { code: "ton", label: "Tongan" },
  { code: "tur", label: "Turkish" },
  { code: "uig", label: "Uyghur" },
  { code: "ukr", label: "Ukrainian" },
  { code: "urd", label: "Urdu" },
  { code: "uzb", label: "Uzbek" },
  { code: "uzb_cyrl", label: "Uzbek (Cyrillic)" },
  { code: "vie", label: "Vietnamese" },
  { code: "yid", label: "Yiddish" },
  { code: "yor", label: "Yoruba" },
].sort((a, b) => a.label.localeCompare(b.label));
