import type { EditorThemeClasses } from "lexical";
import styles from "./DocumentEditor.module.css";

export function createEditorTheme(): EditorThemeClasses {
  return {
    paragraph: styles.editorParagraph,
    heading: {
      h1: styles.heading1,
      h2: styles.heading2,
      h3: styles.heading3,
      h4: styles.heading4,
      h5: styles.heading5,
      h6: styles.heading6,
    },
    quote: styles.editorQuote,
    code: styles.editorCode,
    codeHighlight: {
      default: styles.codeHighlight,
      comment: styles.tokenComment,
      prolog: styles.tokenComment,
      cdata: styles.tokenComment,
      doctype: styles.tokenComment,
      keyword: styles.tokenKeyword,
      atrule: styles.tokenKeyword,
      rule: styles.tokenKeyword,
      important: styles.tokenKeyword,
      string: styles.tokenString,
      char: styles.tokenString,
      "attr-value": styles.tokenString,
      url: styles.tokenString,
      regex: styles.tokenString,
      number: styles.tokenNumber,
      boolean: styles.tokenNumber,
      constant: styles.tokenNumber,
      function: styles.tokenFunction,
      parameter: styles.tokenFunction,
      property: styles.tokenProperty,
      tag: styles.tokenProperty,
      selector: styles.tokenProperty,
      variable: styles.tokenProperty,
      deleted: styles.tokenProperty,
      entity: styles.tokenProperty,
      "named-entity": styles.tokenProperty,
      operator: styles.tokenOperator,
      punctuation: styles.tokenOperator,
      namespace: styles.tokenOperator,
      "class-name": styles.tokenClass,
      "maybe-class-name": styles.tokenClass,
      symbol: styles.tokenClass,
      inserted: styles.tokenClass,
    },
    text: {
      bold: styles.textBold,
      italic: styles.textItalic,
      underline: styles.textUnderline,
      strikethrough: styles.textStrikethrough,
      highlight: styles.textHighlight,
      superscript: styles.textSuperscript,
      subscript: styles.textSubscript,
      code: styles.textCode,
    },
    list: {
      ul: styles.listUl,
      ol: styles.listOl,
      checklist: styles.listUl,
      listitem: styles.listItem,
      listitemChecked: styles.listItemChecked,
      listitemUnchecked: styles.listItemUnchecked,
      nested: {
        list: styles.nestedList,
        listitem: styles.nestedListItem,
      },
    },
    link: styles.editorLink,
    table: styles.table,
    tableRow: styles.tableRow,
    tableCell: styles.tableCell,
    tableCellHeader: styles.tableCellHeader,
    tableCellPrimary: styles.tableCellPrimary,
    tableCellSecondary: styles.tableCellSecondary,
    hr: styles.editorHr,
  };
}
